### PR TITLE
Expand macro using loops

### PR DESCRIPTION
**Pull request by alecdotninja**
This is my attempt to solve a few problems at once.

Expanding the macro as a function call with a closure appealed to me originally because the core concept of the implementation (the "trampoline") could be factored out into support code. I also liked that it avoided introducing any new identifiers and that it didn't create a loop context (that would make `break` valid in places is was not previously).

That said, wrapping the user's code in a closure with a different return type comes with several downsides that I think ultimately outweigh the benefits:
* #5 - In stable Rust, the `?` operator only works in functions that return `Result` or `Option`.
* #9 - The compiler is not always able to infer the inner return type when generics are involved.
* #10 - The compiler cannot deduce that it is safe to move out of the closure in the final return _because it has no way to know statically that that return is in fact final_.  

Thank you, @bbarker, for finding and documenting these issues! The test cases here are lifted directly from his work in #6 .

### CODE REVIEW

**Comment by alecdotninja** [comment]
@bbarker If you have some time to manually test, I'd like to verify that this approach solves #5, #9, and #10 for you. (I would assign you for code review, but for some reason Github is not allowing that.)

**Comment by bbarker** [comment]
Great! I think I found one issue with the PR similar to what I saw before in #7; I can try to get a fix in or post more details sometime today.

**Comment by bbarker** [comment]
I have some code that expands to:

```rust
    fn detab_go<'a, R, W>(
        tab_cnf: &TabConf,
        f_out: &mut W,
        mut bytes_iter: BytesIter<R>,
        mut buf_iter: std::vec::IntoIter<u8>,
        tab_pos_last: usize,
    ) -> Result<(), Error>                                                                                                                                                                    where
        R: Read,
        W: Write,                                                                                                                                                                             {
        let mut tailcall_trampoline_state = (tab_cnf, f_out, bytes_iter, buf_iter, tab_pos_last);                                                                                                 'tailcall_trampoline_loop: loop {
            let (tab_cnf, f_out, mut bytes_iter, mut buf_iter, tab_pos_last) =
                tailcall_trampoline_state;
            return {                                                             
// snip
```

The original code is:

```rust
#[tailcall]
fn detab_go<'a, R, W>(
    tab_cnf: &TabConf,
    f_out: &mut W,
    mut bytes_iter: BytesIter<R>,
    mut buf_iter: std::vec::IntoIter<u8>,
    tab_pos_last: usize,
) -> Result<(), Error>
where
    R: Read,
    W: Write,
{
    match buf_iter.next() {
        Some(byte) => {
            let tab_pos_new = match byte {
                b'\t' => {
                    let tab_pos_new = tab_pos_last + 1;
                    let spc_count = tab_pos_to_space(tab_cnf, tab_pos_new);
                    f_out.write_all(&SPACE_ARRAY[0..spc_count])?;
                    tab_pos_new
                }
                b'\n' => {
                    write_u8(f_out, byte)?;
                    0
                }
                _ => {
                    write_u8(f_out, byte)?;
                    tab_pos_last
                }
            };
            detab_go(tab_cnf, f_out, bytes_iter, buf_iter, tab_pos_new)
        }
        None => {
            match bytes_iter.next() {
                Some(buf_new) => {
                    let buf_iter = buf_new?.into_iter(); //shadow
                    detab_go(tab_cnf, f_out, bytes_iter, buf_iter, tab_pos_last)
                }
                None => Ok(()), /* Finished */
            }
        }
    }
}
```

This results in the following warnings:

```
warning: variable does not need to be mutable
  --> src/tabs.rs:55:5
   |
55 |     mut bytes_iter: BytesIter<R>,
   |     ----^^^^^^^^^^
   |     |
   |     help: remove this `mut`
   |
   = note: `#[warn(unused_mut)]` on by default

warning: variable does not need to be mutable
  --> src/tabs.rs:56:5
   |
56 |     mut buf_iter: std::vec::IntoIter<u8>,
   |     ----^^^^^^^^
   |     |
   |     help: remove this `mut`
```

However, I can't remove the `mut` from the function signature as then it would also be removed from definitions used, which results in this error:

```
  --> src/tabs.rs:63:11
   |
56 |     buf_iter: std::vec::IntoIter<u8>,
   |     -------- help: consider changing this to be mutable: `mut buf_iter`
...
63 |     match buf_iter.next() {
   |           ^^^^^^^^ cannot borrow as mutable

error[E0596]: cannot borrow `bytes_iter` as mutable, as it is not declared as mutable
  --> src/tabs.rs:84:19
   |
55 |     bytes_iter: BytesIter<R>,
   |     ---------- help: consider changing this to be mutable: `mut bytes_iter`
...
84 |             match bytes_iter.next() {
   |                   ^^^^^^^^^^ cannot borrow as mutable
```

This is because we still need `mut` for the values in the `let (/*snip*/) = tailcall_trampoline_state;` statement.

The solution I had along these lines can be seen here: https://github.com/bbarker/tailcall/compare/Result...remove_unnecessary_mut

If that looks good, I can patch that in to this PR if you want, or you can feel free to do it, or maybe there's a better solution.

**Comment by alecdotninja** [comment]
@bbarker Thank you for the detailed explanation! Does this updated version solve the problem?

I think your general approach in #8 is correct. I lifted the test cases, made a few changes around subpath/by_ref, and refactored a bit. Long term, I'd like to support arbitrary patterns, but that will take more work to go through all the `Pat` variants.

**Comment by bbarker** [comment]
That's awesome, it works with no warnings for my code now. 🎆 

Would it be a good time to cut a new release after merging this?

By the way, just to improve my own understanding, I saw that you didn't bother cloning these fields of `PatIdent:

```rust
  attrs: vec![],
  subpat: None,
  by_ref: None,
```

I was being cautious and cloning them in case they were needed, but I guess you already tested that they are not necessary. I tried looking in the docs and didn't see much description about their purpose (maybe I was looking the wrong place). Just curious about these if you have any pointers - thanks!

**Comment by alecdotninja** [comment]
> That's awesome, it works with no warnings for my code now. 

:tada: 

> Would it be a good time to cut a new release after merging this?

That is my plan. I'd like to do some more refactoring, but I don't want to block you on these issues any longer, so I'll merge this and do a release later tonight.

> I was being cautious and cloning them in case they were needed

My intuition for cautious runs the opposite direction here. In general, I think we want the pattern matching to occur when the function is called and the result for the inner state to be as close to exactly the same as the value in the resulting binding as possible which biases copying more rather than less.

Here is the rationale for my handling of each field:
* `attrs` - This represents [attributes](https://doc.rust-lang.org/reference/attributes.html) (`#[something]`) that were added to the pattern (ex `fn f(#[attr] x: i32)`). To my knowledge, there are no compiler attributes that can be added here in stable Rust. My expectation is that if any are added, they are likely to have more to do with the function signature than the binding of the variable itself and should remain only there.
* `subpat` - These are created with the [`@` operator](https://doc.rust-lang.org/reference/patterns.html). Usually, they are used in `match` or `if let` statements [to bind an intermediate value to a variable while matching a more complex pattern](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8100fbca207f1b4843668cf7157081dc), but in function signatures they are (AFAIK) useless since [function arguments must be irrefutable](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=792e090bdca4599c0ef13c0b4f06747b).
* `by_ref` - This refers to whether the `ref` keyword was added to the pattern (ex `fn f(ref x: i32)`). `ref` is the LHS equivalent of the `&` operator. [It causes a reference to a value to be bound instead of the value itself while matching](https://doc.rust-lang.org/reference/patterns.html). Copying `ref` to the later binding would change the meaning of the code slightly -- [we would end up with a reference to a reference](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1a04d64cfa1a10002efd80be103b082d). Moving the `ref` to the later binding would give the correct type, but change the ownership semantics (the value would move/copy into the function).

It occurs to me as I am explaining this that it may be better to reject patterns with `attrs` and `subpat` for the time being. I know of no useful cases where these are specified, and it is probably better err on the side of rejecting the program than doing something unexpected.

**Comment by bbarker** [comment]
Thanks for the explanations, that all sounds good to me. 

As an aside, I'm used to pattern matching in Haskell, where you can lift pattern matching to function arguments like this:

```rust
fn subpat_example(opt_some @ Some(ii): Option<i32>) -> Option<i32> {
    opt_some
}
fn subpat_example(opt_none @ None: Option<i32>) -> Option<i32> {
    opt_none
}
```

Of course, that isn't allowed in Rust, and it would probably feel too verbose in Rust anyway.

**Pull request merged**
