### PR TITLE
Result and Option return types handled; fixes #5

### LINKED ISSUE #5: Functions returning Result may be a special case that needs to be handled differently
Documenting a case I found when using Result:

```rust
#[tailcall]
fn detab_go<'a, I, R, W>(
    f_out: &W,
    bytes_iter: BytesIter<R>,
    buf_iter: I,
    tab_pos_last: usize,
) -> Result<(), Error>
where
    I: Iterator<Item = &'a u8>,
    R: Read,
    W: Write,
{
    todo!();

    match buf_iter.next() {
        Some(byt) => {
            todo!();
            detab_go(f_out, bytes_iter, buf_iter, /*&tab_pos_new*/ todo!())
        }
        None => {
            match bytes_iter.next() {
                Some(buf_new) => {
                    let buf_test: Vec<u8> = buf_new?;
                    let buf_iter = buf_test.iter(); //shadow
                    detab_go(
                        f_out,
                        bytes_iter,
                        buf_iter,
                        /*&tab_pos_new*/ todo!(),
                    )
                }
                None => todo!(),
            }
        }
    }
}
```

This compiles without the `#[tailcall]`, but fails with these errors with it enabled:

```
error[E0277]: the `?` operator can only be used in a closure that returns `Result` or `Option` (or another type that implements `Try`)
  --> src/tabs.rs:59:45
   |                                                                                         
37 | #[tailcall]
   | ----------- this function should return `Result` or `Option` to accept `?`
...
59 |                     let buf_test: Vec<u8> = buf_new?;
   |                                             ^^^^^^^^ cannot use the `?` operator in a closure that returns `Next<(&W, BytesIter<R>, I, usize), _>`
   |
   = help: the trait `Try` is not implemented for `Next<(&W, BytesIter<R>, I, usize), _>`
   = note: required by `from_error`

error[E0308]: mismatched types
  --> src/tabs.rs:64:25
   |
38 | fn detab_go<'a, I, R, W>(
   |                 - this type parameter
...
64 |                         buf_iter,
   |                         ^^^^^^^^ expected type parameter `I`, found struct `std::slice::Iter`
   |
   = note: expected type parameter `I`
                      found struct `std::slice::Iter<'_, u8>`
```

### PR DESCRIPTION
**Pull request by bbarker**
After looking around a bit, it seemed like the best way to handle this was to go with a separate macro annotation. 
We'll also need one for `Option`, which I'm happy to do as part of this PR or another, if desired. I don't know of any other return types that allow for special syntax in a Rust function body. At some point, perhaps when [Try](https://doc.rust-lang.org/std/ops/trait.Try.html) becomes stable (the tracking issue for it appears to be far from complete), a more generic approach may be worth exploring.

Suggestion, if acceptable: Squash & Rebase/Merge

### CODE REVIEW

**Comment by bbarker** [comment]
One thing to note from the benchmarks:

```
RUSTFLAGS="-C opt-level=0" cargo bench _rec

test bench_oddness_rec     ... bench:  24,176,497 ns/iter (+/- 16,186,258)
test bench_oddness_res_rec ... bench:  48,784,726 ns/iter (+/- 29,482,310)
```

The `Result`-based benchmark is twice as slow, but I assume this is largely down to wrapping and unwrapping `Result` many times on a function that really isn't doing much else.

**Comment by bbarker** [comment]
Hi @alecdotninja  - I went ahead and added `Option` support as well as well.

**Comment by alecdotninja** [comment]
@bbarker Thank you for your work here. I'm sorry that I have not taken the time to review it yet. My Github notifications are a mess after joining a larger organization, and I just noticed it yesterday. I'll have some time to review it later this week.

**Comment by bbarker** [comment]
No worries, I've been there before!

**Comment by alecdotninja** [comment]
I haven't forgotten about this, @bbarker . This problem is very interesting, and I'm still thinking about it.

This problem can be solved on nightly trivially:
```rust
impl<Input, Output: std::ops::Try> std::ops::Try for Next<Input, Output> {
    type Ok = <Output as std::ops::Try>::Ok;
    type Error = <Output as std::ops::Try>::Error;

    #[inline(always)]
    fn into_result(self) -> Result<Self::Ok, Self::Error> {
        match self {
            Finish(output) => output.into_result(),
            _ => unreachable!("tailcall::trampoline::Recurse is only valid when immediately returned"),
        }
    }

    #[inline(always)]
    fn from_ok(value: Self::Ok) -> Self {
        Finish(<Output as std::ops::Try>::from_ok(value))
    }

    #[inline(always)]
    fn from_error(error: Self::Error) -> Self {
        Finish(<Output as std::ops::Try>::from_error(error))
    }
}
```

**Comment by bbarker** [comment]
That's great that you found a solution using `Try`; I suppose the Result-based solution you propose could also be easily transformed to support Option, but I haven't thought about that much yet.

Feel free to scrap what I've done so far (this seems far simpler and more future-proof), though if you have a branch that implements Result/Option, I can test it out with my other project.

**Pull request closed without merging**
